// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: deal.proto

public final class Deal {
  private Deal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
